name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.11.0", "<2.0.0"]

seeds: 
  +docs:
    node_color: '#cd7f32'

on-run-start:
  - "{{ generate_non_partition_parquet('customers', 's3://dbt-learn-sample-data/raw_customers.csv') }}"
  - "{{ generate_non_partition_parquet('items', 's3://dbt-learn-sample-data/raw_items.csv') }}"
  - "{{ generate_partition_parquet('orders', 's3://dbt-learn-sample-data/raw_orders.csv', 'ordered_at') }}"
  - "{{ generate_non_partition_parquet('products', 's3://dbt-learn-sample-data/raw_products.csv') }}"
  - "{{ generate_partition_parquet('stores', 's3://dbt-learn-sample-data/raw_stores.csv', 'opened_at') }}"
  - "{{ generate_non_partition_parquet('supplies', 's3://dbt-learn-sample-data/raw_supplies.csv') }}"

models:
  jaffle_shop:
    +pre-hook:
      - "INSTALL https"
      - "LOAD https"
      - "SET s3_region='us-east-2'"
    +materialized: table
    staging:
      +materialized: view
      +docs:
        node_color: 'silver'
    +docs:
      node_color: 'gold'
